steps:
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    args:
      - /bin/sh
      - -c
      - |
        dotnet restore ./JapaneseLearnSystem/JapaneseLearnSystem.sln
        dotnet publish ./JapaneseLearnSystem/JapaneseLearnSystem.sln -c Release -o /app/publish
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/japaneselearnsystem:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/japaneselearnsystem:latest'

images:
  - 'gcr.io/$PROJECT_ID/japaneselearnsystem:latest'

options:
  logging: CLOUD_LOGGING_ONLY
