# cloudbuild.yaml
# 使用 Cloud Build 建置並推送 .NET 8 專案 Docker 映像檔

steps:
  # 1. 使用 .NET SDK 建置並發佈
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    id: 'dotnet-build'
    dir: 'JapaneseLearnSystem'      # 指定工作目錄
    args:
      - /bin/sh
      - -c
      - |
        dotnet restore JapaneseLearnSystem.sln
        dotnet publish JapaneseLearnSystem.sln -c Release -o /app/publish

  # 2. 使用 Docker 建立映像檔
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    dir: 'JapaneseLearnSystem'      # 指定 Dockerfile 所在目錄
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/japaneselearnsystem:latest'
      - '.'

  # 3. 推送映像檔到 GCR
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/japaneselearnsystem:latest'

# 指定最終產生的映像檔
images:
  - 'gcr.io/$PROJECT_ID/japaneselearnsystem:latest'

# 日誌設定
options:
  logging: CLOUD_LOGGING_ONLY
